### ISSUE TITLE
Scrollbar don't work

### ISSUE THREAD

**Issue by jcubic** [huntergregal/huntergregal#1]
You have outdated version of jquery terminal (don't know which version because you have src file). You need update. Try to enter command untill you reach bottom of the page.

in one of old versions I've used code that snif google chrome to select different element when terminal was added to body but in the mean time chrome changed behavior to be like other browsers which broken some old versions of jquery terminal.

**Comment by huntergregal** [comment]
nice! thanks for the heads up my dude

**Comment by huntergregal** [comment]
I updated it - scrolling is working much better.

Noticed in firefox there is a big empty iframe though @jcubic

**Comment by jcubic** [comment]
You need to update css file as well I don't see version and copyright in your css so I can't tell which version you have.
